### ISSUE TITLE
Support Version

### ISSUE THREAD

**Issue by HDVinnie** [akiyamaSM/larapoll#10]
Not a issue just curious if this works out the box with Laravel 5.4

**Comment by akiyamaSM** [comment]
I guess it would, since I've only used Models. 
would you like to try it?

**Comment by HDVinnie** [comment]
Yeah I can. Do you have any sample blade views I could use to make poll

**Comment by akiyamaSM** [comment]
Actually I have not made it yet, I was aiming to work on it in the next release.
or you can help me with that with a PR

**Comment by HDVinnie** [comment]
any updates on sample views?

**Comment by HDVinnie** [comment]
still planning todo sample views?
