### ISSUE TITLE
Standalone install for test

### ISSUE THREAD

**Issue by fhprietor** [akiyamaSM/larapoll#101]
Hi, I am new to laravel.
I want to install and test the system in standalone mode.
I am following the steps. Environment: Windows with XAMP:
> git clone https://github.com/akiyamaSM/larapoll.git
> cd larapoll
> composer require inani / larapoll
"Root package 'inani / larapoll' cannot require itself in its composer.json"

#########################################

Another try: without cloning github:
> mkdir larapoll
> composer require inani / larapoll

Just create a few files:

Mode LastWriteTime Length Name
---- ------------- ------ ----
d ----- 02/17/2021 23:00 vendor
-a ---- 02/17/2021 23:00 61 composer.json
-a ---- 02/17/2021 23:00 28959 composer.lock

#########################################

Third try:
> git clone https://github.com/akiyamaSM/larapoll.git
> cd larapoll
> composer install
> php artisan vendor: publish

"Could not open input file: artisan"

#########################################
Fourth attempt:
With my own laravel 8 project.

> git clone https://github.com/fhprietor/quorum.git
> cd quorum
> composer install
> composer require inani / larapoll

"Using version ^ 2.52 for inani / larapoll
./composer.json has been updated
Running composer update inani / larapoll
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

   Problem 1
     - Root composer.json requires inani / larapoll ^ 2.52 -> satisfiable by inani / larapoll [2.52].
     - inani / larapoll 2.52 requires illuminate / support ~ 5 | ~ 6 -> found illuminate / support [v5.0.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but these were not loaded, likely because it conflicts with another require.

Installation failed, reverting ./composer.json and ./composer.lock to their original content. "

**Comment by akiyamaSM** [comment]
Hello, Larapoll requires Laravel. Thanks.
