### ISSUE TITLE
Could not open input file: artisan

### ISSUE THREAD

**Issue by fhprietor** [akiyamaSM/larapoll#102]
> git clone https://github.com/akiyamaSM/larapoll.git
> cd larapoll
> composer require laravel / framework 6. * (8. * don't install)
> composer require laravel / laravel 6. *
> php artisan migrate

"Could not open input file: artisan"

Please forgive my ignorance, but I feel absolutely powerless.

**Comment by akiyamaSM** [comment]
This package doesn't work alone, it needs to be in a Laravel application.
