### ISSUE TITLE
problem with 2.52 tag preventing latest 2.9.5 from being installed

### ISSUE THREAD

**Issue by vesper8** [akiyamaSM/larapoll#103]
I noticed if you try to run `composer require inani/larapoll` on Laravel 8 it wants to install `^2.52` which doesn't work on Laravel 8 and was tagged back in 2019

The latest release is `2.9.5`. If you explicitly set `2.9.5` as the version then it installs, but if you try something like `^2.9` then it reverts to `^2.52`

I think what happened is that `^2.52` was supposed to be `^2.5.2` ?

As a result of all this, `^2.52` is still considered the latest release. You can see that on https://packagist.org/packages/inani/larapoll too

Not sure how to fix, if you can rename / rectify the faulty tag or what

**Comment by akiyamaSM** [comment]
Thank you for the feedback. to be honest I didn't pay attention to it.
I created a new version that way we avoid every probleme.
Thanks Again!!
