### ISSUE TITLE
Lack of good documentation

### ISSUE THREAD

**Issue by mnaderian** [akiyamaSM/larapoll#107]
This is a good package for polling. But unfortunately we have to learn most of the things from the source code. 
So I propose you start the documentation project and we will help as much as we can. 

Thanks for this good package,
It saved me time.

**Comment by akiyamaSM** [comment]
Thanks for your feedback. Actually, here is a link where i use a demo app to demonstrate how to use it 

https://medium.com/@InaniT0/create-polls-easily-using-laravel-package-larapoll-d8e520f021f5
