### ISSUE TITLE
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

### ISSUE THREAD

**Issue by mpapado3** [akiyamaSM/larapoll#108]
Hi, I am trying to install this package to a project that I have, but I keep stepping on an error when I run composer require.
Below is the full error that I have.

I am trying to install on a Laravel 8 project.

> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException 

  Target class [Illuminate\Database\Eloquent\Factory] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:838
    834▕ 
    835▕         try {
    836▕             $reflector = new ReflectionClass($concrete);
    837▕         } catch (ReflectionException $e) {
  ➜ 838▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    839▕         }
    840▕ 
    841▕         // If the type is not instantiable, the developer is attempting to resolve
    842▕         // an abstract type such as an Interface or Abstract Class and there is

  1   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Inani\Larapoll\LarapollServiceProvider))

      +16 vendor frames 
  18  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Inani\Larapoll\LarapollServiceProvider))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by akiyamaSM** [comment]
Hello, its fixed now :D
