### ISSUE TITLE
Class "Poll" not found

### ISSUE THREAD

**Issue by Xoshbin** [akiyamaSM/larapoll#113]
When I'm trying to use the frontend it's giving the error below, I tried searching all around the package but I didn't find anything mentioning this. just using this command in the view that's all but it's not working. 
`{{ PollWriter::draw(Poll::find(77)) }}
`
This package looks good (even I didn't get what I want yet because of this error)  but it's documentation is very bad it took me an hour to find how the admin panel works. and for the past hour I was looking to fix that issue. so the documentation needs improvement because it's very bad to setup a package in two hours.
If anyone knows how to fix that issue please write it down below, and If I fixed that issue I may send a PR to make the documentation about setting up the admin and the frontend.
Thanks for the package

**Comment by akiyamaSM** [comment]
You are so welcome to Submit PR for documentation. About your issue are you certain you imported the Class?

**Comment by Xoshbin** [comment]
Thank you, I don't know what you mean by importing the class? I installed the package and I used the admin interface to create a question. and used the {{ PollWriter::draw(Poll::find(77)) }} in the blade with the ID of the question. so since I didn't make any controller for the poll and I was expecting the package to generate the question view in the blade template I don't know where to import the class?!! if you mean to import it in the blade please tell me how. please correct me if I'm wrong.
thank you

**Comment by Xoshbin** [comment]
Now I found out that you have to add the code with it's path in the blade then it's working
                        `{{ PollWriter::draw(Inani\Larapoll\Poll::find(6)) }}`

**Comment by akiyamaSM** [comment]
That's what I meant. Good luck.
