### ISSUE TITLE
Check if auth user has voted and then take count of polls ? 

### ISSUE THREAD

**Issue by jyrjsinhatfolium** [akiyamaSM/larapoll#119]
Hi,

Thank you for your package. I encountered an issue that blocks my way forward.

I have tried getting count of polls as of now as shown below:

![image](https://user-images.githubusercontent.com/100403853/164678186-962b4ff1-8f74-4492-b6f0-a0e958349fee.png)

As of Now I am thinking that this below function would have help me but i am not sure.......`

![image](https://user-images.githubusercontent.com/100403853/164675619-761030a0-c88c-40f3-b98b-64f5857e7213.png)

Simply i had made a poll box in my website and i want to show the count of polls in right corner of that box.
1. i need the count of poll in which user has not voted.
2. if user votes on poll it should remove from count as well.

If anyone can help , the response would much appreciated..

Thanks..

**Comment by Temian1** [comment]
goto laracast.com and ask

**Comment by workatfolium** [comment]
> goto laracast.com and ask

okay thanks..

**Comment by jyrjsinhatfolium** [comment]
@Temian1 Thanks for your suggestion but I have solved the issue by the following code....

![image](https://user-images.githubusercontent.com/100403853/165237539-81f006bc-be05-45b7-80e7-712a4f3b6a68.png)

in the ($unvotedpolls) I have got the polls number which current user has not voted.....
