### ISSUE TITLE
example / sample view?

### ISSUE THREAD

**Issue by vesper8** [akiyamaSM/larapoll#12]
Like your package! But would be nice if there was at least a very basic scaffolding / sample view

Even something very basic which I'm sure you've used yourself would be better than nothing?

Even as a reply to this issue :)

Cheers!

**Comment by AkshitSahani** [comment]
I would agree! A little bit more of a guideline of how to use it would be very helpful!

Thanks

**Comment by akiyamaSM** [comment]
Sorry Guys not to be able to respond you as seen as possible, I've not been able to be active in here for the last months.
For @vesper8 & @AkshitSahani 's question Actually I didnt want to add some sample pages thinking that may change from one to an other.
To be honest I thought that no one would use my package, I'm really gratefull for your messages.

**Comment by AkshitSahani** [comment]
I understand. But your package is definitely useful and we're using it for our projects. I am currently using it in a project where polls need to be created, which users can answer and the results of those have to be displayed at the end. I was a little confused about how to use it, so I thought I’d ask you.

I don’t understand how someone would create, edit and close polls. I was able to follow the instructions up to that point, but got confused after. 

Where would the code for creating a new poll with a question and attaching all the possible answers to it go? And once a poll is created, how do I make it visible to users such that they can select an option and vote for it? Lastly, where would the code for getting the results of a poll go? 

Thank you once again

**Comment by akiyamaSM** [comment]
@AkshitSahani an email has been sent answering your question, I'll be guiding you untill you get a good idea about whole the work flow.

**Comment by HDVinnie** [comment]
I have been wanting to use this package for awhile now but also struggled with the view concept. A sample view would be great for displaying polls and results.

**Comment by akiyamaSM** [comment]
@HDVinnie I'm working on it, I think it will be ready in 2 weeks at max, Hopefully.

**Comment by akiyamaSM** [comment]
Done.
