### ISSUE TITLE
Planify polls to be closed at a certaine date

### ISSUE THREAD

**Issue by akiyamaSM** [akiyamaSM/larapoll#16]
Planify Polls not to acept any votes after a certaine date that will provided in the creation/edit.
The admin will be able to prolong the duration of it as well whenever he wants.

**Comment by obiefy** [comment]
How this can happen :
1- running schedule on the server to close poll if it is out of date.
2- Close it inside Poll class using some bootstrapping function.

**Comment by akiyamaSM** [comment]
Actually its now implemented as you mentioned (2) but I still want to make the possibility via (1).
