### ISSUE TITLE
Add the ability to the visitors to vote

### ISSUE THREAD

**Issue by akiyamaSM** [akiyamaSM/larapoll#18]
Visitors as well should be able to vote, not only the users.

**Comment by TnCoders** [comment]
Hello, That's A good Thing do you have some idea to start this ? actualy i was loooking for this.

**Comment by akiyamaSM** [comment]
@TnCoders  Actually didnt start on it yet.

**Comment by akiyamaSM** [comment]
Now its possible to let guest vote.
