### ISSUE TITLE
Class 'PollWriter' not found

### ISSUE THREAD

**Issue by TnCoders** [akiyamaSM/larapoll#50]
Hi, There is Many bugs And This is one of them:

I just added : {{ PollWriter::draw(1, auth()->user()) }}
to Home.blade.php on the vendor view folder.

and got this error.

"Class 'PollWriter' not found"
Exception message: Class 'PollWriter' not found`

**Comment by akiyamaSM** [comment]
Make sure you include the LarapollServiceProvider class in the  config/app.php file.

**Comment by MertcanGokgoz** [comment]
Class 'PoolWriter' not found and i added app.php LarapollServiceProvider

**Comment by kency** [comment]
me too  at lararel5.5

**Comment by kency** [comment]
ok, let's fixit.

also add a alias in config app.php
'aliases' => [
...
'PollWriter'=>Inani\Larapoll\PollWriterFacade::class
]

no tks
