### ISSUE TITLE
Any chance to move Dashboard to another branch?

### ISSUE THREAD

**Issue by mstrychalski** [akiyamaSM/larapoll#51]
You've done very good job making pretty simple thing as package, so nobody needs to do this themselves. But still, dashboard is redundant in most projects, because they already uses their dashboards for handling things.

It would be very nice to move Dashboard to another repo, and just release as another package. This is how it is done usually.

Cheers!

**Comment by akiyamaSM** [comment]
Thanks for the suggestion.
