### ISSUE TITLE
accessing to larapoll

### ISSUE THREAD

**Issue by elyes41** [akiyamaSM/larapoll#52]
i m new in laravel developing and i will use your package, it is installed but i don't know how use it or how to access to this package

**Comment by steph21cc** [comment]
Same here. Can you please add a step by step example on how to use it after installing? Would appreciated so much

**Comment by akiyamaSM** [comment]
@elyes41  and @steph21cc 
Here is a blog post on how to use it, hope its clear. 
https://medium.com/@InaniT0/create-polls-easily-using-laravel-package-larapoll-d8e520f021f5
