### ISSUE TITLE
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN) Class 'App\Http\Requests\Request' not found

### ISSUE THREAD

**Issue by kvinkinamoto** [akiyamaSM/larapoll#55]
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Class 'App\Http\Requests\Request' not found

Not work

**Comment by akiyamaSM** [comment]
It will be supported for Laravel 5.7 soon.
Thanks
