### ISSUE TITLE
PollCreationRequest no contain function $request->all()

### ISSUE THREAD

**Issue by kvinkinamoto** [akiyamaSM/larapoll#56]
/**
     * Store the Request
     *
     * @param PollCreationRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(PollCreationRequest $request)
    {
        $poll = PollHandler::createFromRequest($request->all());
        return redirect(route('poll.index'))
            ->with('success', 'Your poll has been addedd successfully');
    }

**Comment by akiyamaSM** [comment]
Are you sure? Would you please help me with instructions to reproduce the problem?

**Comment by kvinkinamoto** [comment]
sory my english is bad

![image](https://user-images.githubusercontent.com/1387047/43838514-39087c66-9b24-11e8-9292-746500919f3c.png)

use App\Http\Requests\Request;

class PollCreationRequest extends Request

PollManagerController 
public function store(PollCreationRequest $request)
    {
        $poll = PollHandler::createFromRequest($request->all());
        return redirect(route('poll.index'))
            ->with('success', 'Your poll has been addedd successfully');
    }

I don't have use App\Http\Requests\Request; 
and i not undestend where get it.

**Comment by akiyamaSM** [comment]
@kvinkinamoto  Are you usigng Laravel?

**Comment by kvinkinamoto** [comment]
yes 5.6

**Comment by akiyamaSM** [comment]
Actually, I haven't test it on it yet. In the L5.2 it works fine.

**Comment by akiyamaSM** [comment]
It will be supported for Laravel 5.7 soon.
Thanks
