### ISSUE TITLE
$request->user() returning null

### ISSUE THREAD

**Issue by fahadakbar24** [akiyamaSM/larapoll#57]
**Error:**
Call to a member function poll() on null

**Description:**
The error occurs when trying to submit a vote for the poll.

![image](https://user-images.githubusercontent.com/26380184/44369060-74969f00-a4ee-11e8-897e-62c572be72a4.png)

**Comment by akiyamaSM** [comment]
Make sure the user is authenticted.

**Comment by fahadakbar24** [comment]
The user is already authenticated, I am able to access the authenticated user using the Auth::user() and $request->user() in my own code but the plug-in is seeing it as unauthenticated.

**Comment by akiyamaSM** [comment]
It will be supported for Laravel 5.7 soon.
Thanks
