### ISSUE TITLE
Surveys support

### ISSUE THREAD

**Issue by obiefy** [akiyamaSM/larapoll#63]
I installed this package on L5.7 and I played around the implementation and source code.
In my case, I need to use this package for surveys so the single survey may have multiple polls.
For example:
```PHP
// create survey and attach the poll
$survey->addPoll(Poll::create([
            'question' => 'What is the best PHP framework?'
]));
```
So do you have any plan for this?, I can contribute to making this happen.
please reply ASAP.

**Comment by akiyamaSM** [comment]
I'd be happy to accept a PR. To be honest its in my mind to make it as a suervey.

**Comment by obiefy** [comment]
That's great, let start analyzing this.
--- Survey
|----- database table columns
|-------- title
|-------- title
|
|
|
|

**Comment by obiefy** [comment]
That's great, let us start.
