### ISSUE TITLE
Return warning alert when poll object not found on database

### ISSUE THREAD

**Issue by obiefy** [akiyamaSM/larapoll#64]
I found this exception when I am trying to use `PollWriter::draw($poll_id)` method on a nonexistent poll.
I think it will be good if this method returned a warning alert instead of `no results` exception.

![Screenshot (3)](https://user-images.githubusercontent.com/16496932/55660885-2d171600-5826-11e9-8600-0aa8754f3987.png)

**Comment by akiyamaSM** [comment]
Its an option, Or to hide it totally. you can provide a PR I'll be happy to merge it.

**Comment by obiefy** [comment]
I started work it, I think it is a good idea to use `type hinting` on this method.

**Comment by akiyamaSM** [comment]
Fixed with #65
