### ISSUE TITLE
CRUD UI optional

### ISSUE THREAD

**Issue by akiyamaSM** [akiyamaSM/larapoll#72]
I don't think we must separate both API and the CRUD UI since it's not that big. so I suggest to make it optional via configuration.

**Comment by archisss** [comment]
i'm looking for a poll system i'm going to fork your project and like to participate in it, can i; you are accepting pull request.

i can start creating a illustrated installation a first poll create, i have to do it anyway.

**Comment by akiyamaSM** [comment]
I'll be happy to review your PR
