### ISSUE TITLE
Class 'Inani\Guest' not found

### ISSUE THREAD

**Issue by angeljasth** [akiyamaSM/larapoll#76]
When poll includes option "allow to guest", function resolveVoter returns error 'Class Inani\Guest' not found.

**Comment by akiyamaSM** [comment]
Problem solved with the latest PR #77, Thanks  for the feedback.

**Comment by spmsupun** [comment]
still having the issue in 2.5

**Comment by milanchheda** [comment]
Still getting this error.

**Comment by lloricode** [comment]
same here

**Comment by lloricode** [comment]
did this released? @akiyamaSM

**Comment by lloricode** [comment]
still getting this

```php

namespace Inani\Larapoll\Http\Controllers;

use App\Http\Controllers\Controller;
use Exception;
use Illuminate\Http\Request;
use Inani\Guest; <----
use Inani\Larapoll\Poll;

```

in inani/larapoll: 2.5

**Comment by akiyamaSM** [comment]
Hello @lloricode would you open a new issue with the use case to be able to reproduce it.
