### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by akiyamaSM** [akiyamaSM/larapoll#78]
For the moment I will not accept any PR untill we re-write the tests to be sure that the new code doesn't break the old one.

I'll be happy to Accept PR related to tests.

**Comment by obiefy** [comment]
It is important to add [Travis CI](https://travis-ci.com).

**Comment by akiyamaSM** [comment]
@obiefy exactly.

**Comment by AboElnoor** [comment]
Contributing file isn't clear, branches as well.

**Comment by akiyamaSM** [comment]
@AboElnoor What is not clear?

**Comment by AboElnoor** [comment]
> @AboElnoor What is not clear?
How to contribute, and which standers should we follow?
What is the description of every branch and which branch to create PR for?

**Comment by akiyamaSM** [comment]
@AboElnoor You can create PR for Master ;) there is no standar for the right moment.

**Comment by AboElnoor** [comment]
> @AboElnoor You can create PR for Master ;) there is no standard for the right moment.


I did before, but you didn't interact with it.

**Comment by akiyamaSM** [comment]
when? can you refer to the PR?

**Comment by obiefy** [comment]
@AboElnoor I think you mean contribution guide

**Comment by AboElnoor** [comment]
> when? can you refer to the PR?

I think I was making something wrong, I'll try to make it again.

> @AboElnoor I think you mean contribution guide

Exactly, thanks for the clarification.
