### ISSUE TITLE
Frontend use

### ISSUE THREAD

**Issue by rabol** [akiyamaSM/larapoll#81]
Hi

As i want guest users to be able to vote I grabbed the dev-master version.

{{ PollWriter::draw(1) }}

does not work:

Inani\Larapoll\Helpers\PollWriter::draw() must be an instance of Inani\Larapoll\Poll, int given,

Did the usage change or is the read me wrong ?

**Comment by akiyamaSM** [comment]
Hey @rabol sorry I haven't changed the readme yet, now you should pass an instance of poll. I'll make it accept an id too later. thanks.

**Comment by rabol** [comment]
No problem :)

I changed so I pass a Poll instance, but all I get is:

"Thanks for voting"

**Comment by rabol** [comment]
ok.. I needed to update the poll
Seems to be working

**Comment by akiyamaSM** [comment]
Thanks ^^. I'll be closing the issue then.

**Comment by cedlinx** [comment]
Hello All,

I know this closed but I've been stuck at "Thanks for voting" (even though I've not yet voted) and would like to know how @rabol got past that.

Thank you.
