### ISSUE TITLE
Illuminate\Database\Eloquent\Collection::isComingSoon does not exist

### ISSUE THREAD

**Issue by almi9** [akiyamaSM/larapoll#83]
Hi

I trying to drow the poll

   {{ PollWriter::draw(\Inani\Larapoll\Poll::find(1)) }}

I found that error

Illuminate\Database\Eloquent\Collection::isComingSoon does not exist

Anyone can help me, please?

**Comment by akiyamaSM** [comment]
Hello, You can still pass an id 

{{ PollWriter::draw(1) }}

**Comment by almi9** [comment]
Hi 

Thank you for your replay


I found that error

 Illuminate\Database\Query\Builder::hasVoted does not exist. 
when I use 
{{ PollWriter::draw(1) }}

thank you a lot for your suport

**Comment by akiyamaSM** [comment]
Make sure to use the latest version. and setting up the model correctly.

**Comment by almi9** [comment]
Hi

That is the steps that I used to install it

'I used laravel 5.6'
1-run 
composer require inani/larapoll

2-php artisan vendor:publish

```
Copied File [\vendor\inani\larapoll\src\database\migrations\2017_01_23_115718_create_polls_table.php] To [\database\migrations\2017_01_23_115718_create_polls_table.php]
Copied File [\vendor\inani\larapoll\src\database\migrations\2017_01_23_124357_create_options_table.php] To [\database\migrations\2017_01_23_124357_create_options_table.php]
Copied File [\vendor\inani\larapoll\src\database\migrations\2017_01_25_111721_create_votes_table.php] To [\database\migrations\2017_01_25_111721_create_votes_table.php]
Copied File [\vendor\inani\larapoll\src\config\config.php] To [\config\larapoll_config.php]
```

3- enter http://127.0.0.1:8000/admin_polls/admin/polls
4-write new poll
5- add drow code "{{ PollWriter::draw(1) }}" on
blog\vendor\inani\larapoll\src\views\dashboard\options ->index

I upload the code here

https://we.tl/t-iRWG3gpspm

can you advise me what I do wrong

thank you a lot

**Comment by mrwhale** [comment]
Check out the first half of issue #80 I had the same error. When installing try appending `dev-master` to it to grab the latest version

`composer require inani/larapoll dev-master`

**Comment by domsfd** [comment]
Hi almi9 could you please share the project source code that you have uplaod before, regards
