### ISSUE TITLE
Unable to install larapolll

### ISSUE THREAD

**Issue by domsfd** [akiyamaSM/larapoll#85]
Hi, I've followed all the steps but when include the code bellow in my index controller:
$poll = new Poll([
            'question' => 'What is the best PHP framework?'
        ]);
the error bellow appear:
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'App\Http\Controllers\Poll' not found

Are i missing part of declaration? please advise

**Comment by obiefy** [comment]
Hi, @domsfd Did you import `Poll` class correctly?
please make sure you add `use Inani\Larapoll\Poll;` inside your controller.

**Comment by domsfd** [comment]
Hi obiefy, thank you for the answer, also could you please provide full project showing all the steps for polling process with larapoll in ordre for me to have a clear understanding of larapoll ? Thanks in adavance

**Comment by obiefy** [comment]
This is article from the package Creator, it will help you.
https://medium.com/@InaniT0/create-polls-easily-using-laravel-package-larapoll-d8e520f021f5

**Comment by domsfd** [comment]
I have already seen this article but no idea on which code (controler and view) to use for example to obtain the first window "create Poll" ?

**Comment by domsfd** [comment]
For example this code:
// a voter(user) picks a poll to vote for
// only ids or array of ids are accepted
$voter->poll($poll)->vote($voteFor->getKey());
Do i need to create one controller to pick a pool ?

**Comment by domsfd** [comment]
Please provide description of the code below
// a voter(user) picks a poll to vote for
// only ids or array of ids are accepted
$voter->poll($poll)->vote($voteFor->getKey());

Could you please correct and complete my vote function bellow:

Public function vote(Poll $poll,$voter, $voteFor) {
// is $voteFor = the $option ??? 
// is $voter part of input function ?
$voter->poll($poll)->vote($voteFor->getKey());
 return view('poll_result'['poll => $poll])
}
