### ISSUE TITLE
A guide to install the UI

### ISSUE THREAD

**Issue by ranrinc** [akiyamaSM/larapoll#89]
Is there a guide to install the UI.. I try https://medium.com/@InaniT0/create-polls-easily-using-laravel-package-larapoll-d8e520f021f5 which show the nice UI but no guide on how to make it run. 

I hope someone will help

**Comment by akiyamaSM** [comment]
I don't understand the problem?

Thanks for the usage.

**Comment by ranrinc** [comment]
I mean.. after running composer and all the step.. how can we see the admin UI and poll UI? Is there a guide on how to make them appear? is there a routes that need to be set? or view to be created? Maybe some guide?

**Comment by akiyamaSM** [comment]
Please follow the readme instructions 
https://github.com/akiyamaSM/larapoll#crud-handler

**Comment by ranrinc** [comment]
> Please follow the readme instructions
> https://github.com/akiyamaSM/larapoll#crud-handler

Where should I put  `{{ PollWriter::draw(Poll::find(77)) }}` or `{{ route('poll.vote', $id) }}`

How do I make the poll? How do you make/called the pages shown on https://medium.com/@InaniT0/create-polls-easily-using-laravel-package-larapoll-d8e520f021f5?

**Comment by akiyamaSM** [comment]
Its up to you to where you want the code to be shown,
The UI is just a helper, its up to you to decide how to use the the polls. you can even make your own.

**Comment by ranrinc** [comment]
> Its up to you to where you want the code to be shown,
> The UI is just a helper, its up to you to decide how to use the the polls. you can even make your own.

In your example, how do you make them appear? is there an example? a web.php or the view? or any controller?

**Comment by akiyamaSM** [comment]
it should be like this http://yoursite.com/prefix/admin
