### ISSUE TITLE
can you tag a new version for Laravel 6?

### ISSUE THREAD

**Issue by vesper8** [akiyamaSM/larapoll#90]
@akiyamaSM I see you've added support but one cannot install this unless they specify dev-master. Could you please tag a new release?

And since Laravel 7 is right around the corner you may as well change the composer.json to support Laravel 7 too

Thank you

**Comment by akiyamaSM** [comment]
Sorry for being late, its done

**Comment by vesper8** [comment]
thanks much!

**Comment by vesper8** [comment]
@akiyamaSM Laravel 7 just came out : ) would be great if you could support it quickly, yours is one of 3 dependencies preventing me from upgrading right now. Thanks!
