### ISSUE TITLE
Laravel 7 compatibility

### ISSUE THREAD

**Issue by vesper8** [akiyamaSM/larapoll#91]
`2.5.2` is not compatible with Laravel 7 due to `illuminate/support ~5|~6`

@akiyamaSM Could you please release a new version with Laravel 7 compatibility?

Thanks a lot!

**Comment by vesper8** [comment]
@akiyamaSM any update on adding Laravel 7 compatibility, please? Yours is the last package I need to be updated before I can proceed with the upgrade to 7, would really appreciate if you could find the time to add it soon. Many thanks

**Comment by akiyamaSM** [comment]
@vesper8 
Hello, Sorry for being late, its now supported by Laravel 7.
if there is any issue let me know to fix it.
new version will be dropped in the next few weeks anyway ;)

**Comment by vesper8** [comment]
awesome!! thanks for the quick turnaround!
